module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/*.test.ts', '**/*.spec.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/server.ts',
    '!src/app.ts',
    '!src/**/*.controller.ts',
    '!src/**/*.routes.ts',
    '!src/**/seed-*.ts',
    '!src/scripts/**',
    '!src/config/**',
    '!src/middlewares/**',
    '!src/modules/auth/**',
    '!src/modules/catalogs/**',
    '!src/modules/companies/**',
    '!src/modules/demo/**',
    '!src/modules/users/**',
    '!src/modules/plans/**',
    '!src/modules/operations/**',
    '!src/modules/reports/**/**.controller.ts',
    '!src/modules/reports/**/**.routes.ts',
    '!src/types/**',
    '!src/utils/logger.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 5,
      functions: 2,
      lines: 4,
      statements: 5,
    },
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@fin-u-ch/shared$': '<rootDir>/../../packages/shared/src',
    '^@fin-u-ch/shared/(.*)$': '<rootDir>/../../packages/shared/src/$1',
  },
  testPathIgnorePatterns: ['/node_modules/', '/dist/', 'hash.test.ts'],
  coveragePathIgnorePatterns: ['/node_modules/', '/dist/', 'hash.ts'],
};

