name: Test Health Check

on:
  workflow_dispatch:

jobs:
  test:
    name: Test API Health
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Wait for services to be ready
        run: |
          echo "Waiting 30 seconds for services to fully start..."
          sleep 30

      - name: Test health endpoint
        run: |
          echo "Testing health check..."
          for i in {1..3}; do
            echo "Attempt $i/3..."
            if curl -f http://${{ secrets.VPS_HOST }}/api/health; then
              echo "✅ Health check passed!"
              exit 0
            fi
            if [ $i -lt 3 ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "❌ Health check failed"
          exit 1

      - name: Test root endpoint
        run: |
          echo "Testing root endpoint..."
          curl -v http://${{ secrets.VPS_HOST }}/ || echo "Root endpoint failed"
