# ================================================
# Docker Compose для ИНФРАСТРУКТУРЫ (гибридный режим)
# ================================================
# Запускает только PostgreSQL и Redis для локальной разработки
# Приложения запускаются локально с hot reload

services:
  postgres:
    image: postgres:15-alpine
    container_name: fin-u-ch-postgres-hybrid
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fin_u_ch_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432' # Стандартный порт для гибридного режима
    volumes:
      - postgres_data_hybrid:/var/lib/postgresql/data
    networks:
      - fin-u-ch-hybrid
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fin-u-ch-redis-hybrid
    ports:
      - '6379:6379' # Стандартный порт для гибридного режима
    networks:
      - fin-u-ch-hybrid
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_hybrid:

networks:
  fin-u-ch-hybrid:
    driver: bridge
